version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
       # Group all dependencies in one PR.
       nuget-dependencies:
          patterns:
             - "*"
    ignore:
        # Don't update to continue to support .Net 8
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
