version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
       # Group all dependencies in one PR.
       nuget-dependencies:
          patterns:
             - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
