// Copyright (c) Sven Groot (Ookii.org)
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Ookii.Jumbo.Jet.Tasks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "multi", Scope = "member", Target = "Ookii.Jumbo.Jet.JobConfiguration.#AddStage(System.String,System.Collections.Generic.IEnumerable`1<Ookii.Jumbo.Jet.StageConfiguration>,System.Type,System.Int32,Ookii.Jumbo.Jet.Channels.ChannelType,Ookii.Jumbo.Jet.Channels.ChannelConnectivity,System.Type,System.Type,System.String,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.ChannelInputConfiguration.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.ChannelInputConfiguration.#MultiInputRecordReaderTypeName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.InputStageInfo.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.JobConfiguration.#AddStage(System.String,System.Type,System.Int32,System.Collections.Generic.IEnumerable`1<Ookii.Jumbo.Jet.InputStageInfo>,System.Type,System.String,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.StageConfiguration.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.ChannelConfiguration.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "Ookii.Jumbo.Jet.Channels.IChannelMultiInputRecordReader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.OutputChannel.#CreateMultiRecordWriter`1(System.Collections.Generic.IEnumerable`1<Ookii.Jumbo.IO.RecordWriter`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Ookii.Jumbo.Jet.MergeRecordReader`1.#CreateMergeQueue(System.Int32,Ookii.Jumbo.Jet.MergeRecordReader`1<!0>+MergeInputComparer,System.Int32&,System.Int32&,System.Int32,System.Collections.Generic.List`1<Ookii.Jumbo.Jet.MergeRecordReader`1<!0>+PreviousMergePassOutput>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Ookii.Jumbo.Jet.MergeRecordReader`1.#ProcessInputsForMergePass(System.Int32,Ookii.Jumbo.Jet.MergeRecordReader`1<!0>+MergeInputComparer,System.Int32&,System.Collections.Generic.SortedList`2<System.Int32,System.Collections.Generic.List`1<Ookii.Jumbo.Jet.MergeRecordReader`1<!0>+PreviousMergePassOutput>>,System.Int32,System.Int32&,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperation.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.JobBuilder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperation.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.SetOutput(Ookii.Jumbo.Jet.Jobs.Builder.IOperationOutput)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperation.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.Stage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperation.#Ookii.Jumbo.Jet.Jobs.Builder.IOperationInput.RecordType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.Channel.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.FileChannelOutputType.#MultiFile")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.InputStageInfo.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.SpillRecordWriterFlags.#AllowMultiRecordIndexEntries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.StageConfiguration.#MultiInputRecordReaderType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "Ookii.Jumbo.Jet.MultiPartitionRecordReader`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.JobConfiguration.#AddStage(System.String,System.Type,System.Int32,System.Collections.Generic.IEnumerable`1<Ookii.Jumbo.Jet.Jobs.InputStageInfo>,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.SpillRecordWriterOption.#AllowMultiRecordIndexEntries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "Ookii.Jumbo.Jet.Channels.SpillRecordWriterOption")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Ookii.Jumbo.Jet.Channels.SpillRecordWriterOptions.#AllowMultiRecordIndexEntries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperationBase.#Ookii.Jumbo.Jet.Jobs.Builder.IOperationInput.RecordType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperationBase.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.Stage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperationBase.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.SetOutput(Ookii.Jumbo.Jet.Jobs.Builder.IOperationOutput)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Ookii.Jumbo.Jet.Jobs.Builder.StageOperationBase.#Ookii.Jumbo.Jet.Jobs.Builder.IJobBuilderOperation.JobBuilder")]
