//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.Jumbo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.Jumbo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; provided for argument &apos;{1}&apos; could not be interpreted as a {2}..
        /// </summary>
        internal static string ArgumentConversionErrorFormat {
            get {
                return ResourceManager.GetString("ArgumentConversionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the last positional argument may be an array..
        /// </summary>
        internal static string ArrayNotLastArgument {
            get {
                return ResourceManager.GetString("ArrayNotLastArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,13} : {1}.
        /// </summary>
        internal static string DefaultArgumentDescriptionFormat {
            get {
                return ResourceManager.GetString("DefaultArgumentDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DefaultArraySuffix {
            get {
                return ResourceManager.GetString("DefaultArraySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string DefaultOptionalArgumentFormat {
            get {
                return ResourceManager.GetString("DefaultOptionalArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}={1}].
        /// </summary>
        internal static string DefaultOptionalArgumentWithDefaultValueFormat {
            get {
                return ResourceManager.GetString("DefaultOptionalArgumentWithDefaultValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string DefaultRequiredArgumentFormat {
            get {
                return ResourceManager.GetString("DefaultRequiredArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}.
        /// </summary>
        internal static string DefaultUsagePrefixFormat {
            get {
                return ResourceManager.GetString("DefaultUsagePrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument name cannot be empty..
        /// </summary>
        internal static string EmptyArgumentName {
            get {
                return ResourceManager.GetString("EmptyArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedArgumentSwitch may not be empty..
        /// </summary>
        internal static string EmptyNamedArgumentSwitch {
            get {
                return ResourceManager.GetString("EmptyNamedArgumentSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value does not have the same type as the argument for argument {0}..
        /// </summary>
        internal static string IncorrectDefaultValueTypeFormat {
            get {
                return ResourceManager.GetString("IncorrectDefaultValueTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent must be greater than or equal to zero..
        /// </summary>
        internal static string IndentOutOfRange {
            get {
                return ResourceManager.GetString("IndentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not supported for command line arguments..
        /// </summary>
        internal static string InvalidArrayRank {
            get {
                return ResourceManager.GetString("InvalidArrayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line constructor cannot have non-optional arguments after an optional argument..
        /// </summary>
        internal static string InvalidOptionalArgumentOrder {
            get {
                return ResourceManager.GetString("InvalidOptionalArgumentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum line length must be larger than zero..
        /// </summary>
        internal static string MaxLineLengthOutOfRange {
            get {
                return ResourceManager.GetString("MaxLineLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent must be smaller than the maximum line length..
        /// </summary>
        internal static string MaxLineLengthSmallerThanIndent {
            get {
                return ResourceManager.GetString("MaxLineLengthSmallerThanIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} has no value..
        /// </summary>
        internal static string MissingArgumentValueFormat {
            get {
                return ResourceManager.GetString("MissingArgumentValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified property is not a named argument..
        /// </summary>
        internal static string MissingNamedArgumentAttribute {
            get {
                return ResourceManager.GetString("MissingNamedArgumentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor with the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string MultipleMarkedConstructors {
            get {
                return ResourceManager.GetString("MultipleMarkedConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named argument &apos;{0}&apos; cannot contain a colon (:)..
        /// </summary>
        internal static string NamedArgumentContainsSeparatorFormat {
            get {
                return ResourceManager.GetString("NamedArgumentContainsSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedArgumentSwitch may not contain a colon (&apos;:&apos;)..
        /// </summary>
        internal static string NamedArgumentSwitchContainsSeparator {
            get {
                return ResourceManager.GetString("NamedArgumentSwitchContainsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} specifies no named or positional command line arguments..
        /// </summary>
        internal static string NoArgumentsFormat {
            get {
                return ResourceManager.GetString("NoArgumentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments type does not have any public constructors..
        /// </summary>
        internal static string NoConstructor {
            get {
                return ResourceManager.GetString("NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor, none of which has the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string NoMarkedConstructor {
            get {
                return ResourceManager.GetString("NoMarkedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} has type {1} that cannot be parsed from a string..
        /// </summary>
        internal static string NoTypeConverterFormat {
            get {
                return ResourceManager.GetString("NoTypeConverterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument {0}..
        /// </summary>
        internal static string UnknownArgumentFormat {
            get {
                return ResourceManager.GetString("UnknownArgumentFormat", resourceCulture);
            }
        }
    }
}
